### ISSUE TITLE
UX for the https://mediaserver.express is not so good.

### ISSUE THREAD

**Issue by laurencefass** [mediafoundation/mediaserver#3]
Im seeking a demo of this and I have set up OBS studio with correct details from https://mediaserver.express

When I visit link i can see the broadcast which only appears after a very long delay and then is intermittent, choppy and slow. Its not useable as a video stream.  When I disconnect the stream at source and then restrart it, the stream link continued to render the previous stream and then lock up. Is this expected network behaviour at this stage? If not what should I be expecting from this demo in terms of performance? Certainly not getting an "instant broadcast" experience.

Maybe this is because the network is small with not many nodes?  Im very grateful for feedback and very happy to be of further assistacnce with testing if i can.

**Comment by heyongjun520** [comment]
media to the moon

**Comment by laurencefass** [comment]
this is not the place for fanboys please use facebook.

**Comment by laurencefass** [comment]
is this project still being maintained/supported?

**Comment by mediafoundation** [comment]
Hey thanks for your comment. The issues you're describing looks like a network problem in your end, check out our sample stream at https://mediaserver.express/v/MdF4J9kn
Can you try again/with other hardware / connection to broadcast?

**Comment by laurencefass** [comment]
Thanks thats very impressive! I'll try experimenting with settings....
